name: docker-compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    channels-dvr:
      image: fancybits/channels-dvr:latest
      container_name: channels-dvr
      network_mode: host
      ports:
        - "8089:8089"
      restart: on-failure:10
      devices:
        - /dev/dri:/dev/dri
      volumes:
        - /mnt/disk/dvr/config:/channels-dvr
        - /mnt/disk/dvr/recordings:/shares/DVR
